- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: false
   
  tasks:
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/gnome.yml
    - include_tasks: tasks/tilix-config.yml
    - include_tasks: tasks/bash-aliases.yml
