- name: Install direnv
  apt:
    name:
      - direnv

- name: Add comment for the direnv hook
  become: true
  become_user: martin
  ansible.builtin.shell:
    cmd: |
      grep -qxF '# Direnv hook' ~/.bashrc || echo '\n# Direnv hook' >> ~/.bashrc

- name: Add gradle alias
  become: true
  become_user: martin
  ansible.builtin.shell:
    cmd: |
      grep -qxF 'eval "$(direnv hook bash)"' ~/.bashrc || sed -i '/# Direnv hook/a eval "$(direnv hook bash)"' ~/.bashrc