- name: configure dark color scheme
  become: true
  become_user: martin
  community.general.dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"
    state: present

- name: configure gtk-theme
  become: true
  become_user: martin
  community.general.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Yaru-dark'"
    state: present

- name: configure icon-theme
  become: true
  become_user: martin
  community.general.dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Yaru-dark'"
    state: present

- name: configure dock icon size
  become: true
  become_user: martin
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size"
    value: 34
    state: present

- name: configure dock position
  become: true
  become_user: martin
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-position"
    value: "'BOTTOM'"
    state: present

- name: configure favorites
  become: true
  become_user: martin
  community.general.dconf:
    key: "/org/gnome/shell/favorite-apps"
    value: "['intellij-idea-ultimate_intellij-idea-ultimate.desktop', 'firefox.desktop', 'spotify_spotify.desktop', 'org.gnome.Nautilus.desktop', 'keepassxc_keepassxc.desktop']"
    state: present
