- name: configure dark color scheme
  become: false
  community.general.dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"
    state: present
  environment:
    DBUS_SESSION_BUS_ADDRESS: "{{ lookup('env', 'DBUS_SESSION_BUS_ADDRESS') }}"

- name: configure gtk-theme
  become: false
  community.general.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Yaru-dark'"
    state: present
  environment:
    DBUS_SESSION_BUS_ADDRESS: "{{ lookup('env', 'DBUS_SESSION_BUS_ADDRESS') }}"

- name: configure icon-theme
  become: false
  community.general.dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Yaru-dark'"
    state: present
  environment:
    DBUS_SESSION_BUS_ADDRESS: "{{ lookup('env', 'DBUS_SESSION_BUS_ADDRESS') }}"
