- name: Install apt packages
  apt:
    name:
      - git
      - tilix
      - meld
      - python3-psutil
      
- name: Install snap packages
  community.general.snap:
    name:
      - steam
      - keepassxc
      - spotify

- name: Install IntelliJ IDEA
  community.general.snap:
    name:
      - intellij-idea-ultimate
    classic: true
