- name: Install apt packages
  apt:
    name:
      - git
      - tilix
      - meld
      - python3-psutil
      - libreoffice
      - pdfarranger
      - curl
      - simple-scan
      
- name: Install java 21
  apt:
    name:
      - openjdk-21-jdk
      - openjdk-21-source

- name: Install java 17
  apt:
    name:
      - openjdk-17-jdk
      - openjdk-17-source

- name: Set java 21 as default
  community.general.alternatives:
    name: java
    path: /usr/lib/jvm/java-21-openjdk-amd64/bin/java
      
- name: Install snap packages
  community.general.snap:
    name:
      - steam
      - keepassxc
      - spotify

- name: Install IntelliJ IDEA
  community.general.snap:
    name:
      - intellij-idea-ultimate
    classic: true
