- name: Set tilix as default terminal
  community.general.alternatives:
    name: x-terminal-emulator
    path: /usr/bin/tilix.wrapper
    
- name: Create symlink for vte
  become: true
  ansible.builtin.shell:
    cmd: '[ -L /etc/profile.d/vte.sh ] || ln -s /etc/profile.d/vte-2.91.sh /etc/profile.d/vte.sh'

- name: update .bashrc
  ansible.builtin.shell:
    cmd: "grep -qxF 'if [ $TILIX_ID ] || [ $VTE_VERSION ]; then' ~/.bashrc || echo -e '\nif [ $TILIX_ID ] || [ $VTE_VERSION ]; then\n    source /etc/profile.d/vte.sh\nfi' >> ~/.bashrc"
